### ISSUE TITLE
Add support for DRV8825

### ISSUE THREAD

**Issue by kwahoo2** [kwahoo2/Mortar#1]
**Reason:**
Better availability by independent board manufacturers than DRV8814.

Datasheet: https://www.ti.com/lit/ds/slvsa73f/slvsa73f.pdf

**Differences:**
Current implementation of DRV8814 driver uses continuous (floating point) microstepping.  PWM of relevant phases is adjusted with precision dependent of pigpio library.

DRV8825 uses fixed size (up to 32) microstepping. Number of microsteps is defined by state of pins MODE0, MODE1, MODE2.

**Comment by Apnet66** [comment]
Yes, 8825 drivers are available on ready-made boards. I wanted to do it on these drivers.

**Comment by Apnet66** [comment]
(https://www.amazon.co.uk/Stepper-Motor-HAT-Controller-Microstepping/dp/B07PXF5DZ7)

**Comment by kwahoo2** [comment]
Initial implementation of DRV8825 is here.
6f5ed32e0666fbce27c1c71ca0afe603ac62df9a
c7b1fceec31b944652e066ae86567b6ad641d268

DRV8825 has to be chosen in the preferences window.
![mortarprefs](https://github.com/kwahoo2/Mortar/assets/3474114/d715d256-7e28-449c-81e5-68db752d71df)

I am not closing the issue, since I am going to add (compile-time) option for pinout of the HAT @Apnet66 linked above. 

As for now moment the code reuses old pins, so:

    ALT ENBL: GPIO 4, physical pin 7
    ALT DIR: GPIO 5, physical pin 29
    ALT STEP:  GPIO 6, physical pin 31
    AZI ENBL: GPIO 20, physical pin 38
    AZI DIR: GPIO 12, physical pin 32
    AZI STEP: GPIO 26, physical pin 37

Known limitations compared to DRV8814:
- no software current limiter, since DRV8825 requires reference voltage, so DAC would be needed
- motors run synchronously at constant speed, they use lower value of max speed for ALT and AZI set in the preferences tab.

My prototype uses two DRV8825 StepStick boards;)
![20231125_225450](https://github.com/kwahoo2/Mortar/assets/3474114/4203bb3a-df83-4406-8f5e-6d4059472767)

**Comment by Apnet66** [comment]
Thank you.  I will try. I also have 2100 modules, they are 1/64 steps, it will be possible to achieve a result like 8814. The connection to the strawberry is not visible in the photo.

**Comment by kwahoo2** [comment]
> (https://www.amazon.co.uk/Stepper-Motor-HAT-Controller-Microstepping/dp/B07PXF5DZ7)

Implemented now as DRV8825 HAT (not tested on real hardware)
There is pin-out tip after selecting the driver 
![drv8825hat](https://github.com/kwahoo2/Mortar/assets/3474114/a010401d-c02f-4f56-81d2-7e8c919bb6b4)

**Comment by Apnet66** [comment]
Hi. I ordered this module for an experiment.  I'll try to assemble it using mechanics from another project, and recalculate the transmission link there.  previous project, does not work with Stellarium.  It works from the monitor, but the Developer has disappeared..You are running your project well.We will do it.
