### ISSUE TITLE
synchronization with Stellarium

### ISSUE THREAD

**Issue by Apnet66** [kwahoo2/Mortar#2]
Merry Christmas to everyone!
There are problems, there is no synchronization with Stellarium.

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Stellarium tracked object url: QUrl("http://localhost:8090/api/objects/info?name=New Telescope 1&format=json")
Board version:  79
degPerStepAzi 0.0204545
degPerStepAlt 0.0170455
Did not find any connected gamepads
Port set to  "ttyS0"
Port set to  "ttyS0"
Fast decay: false
Stellarium tracked object url: QUrl("http://192.168.0.106:8090/api/objects/info?name=New Telescope 1&format=json")
Stellarium tracked object url: QUrl("http://192.168.0.106:8090/api/objects/info?name=New Telescope 1&format=json")
Driver id: 1
Using driver id: 1
error: XDG_RUNTIME_DIR is invalid or not set in the environment.

**Comment by Apnet66** [comment]
![17035252665562688195476055074132](https://github.com/kwahoo2/Mortar/assets/54183366/659d2f40-58b0-4596-82ab-7293caaa5da1)

**Comment by kwahoo2** [comment]
Hi,
Can you open the url in a web browser? `http://192.168.0.106:8090/api/objects/info?name=New Telescope 1&format=json`
You should see something like this:
![mortar_scrot](https://github.com/kwahoo2/Mortar/assets/3474114/f7ef6653-413e-4a9d-8cf7-0f05a372dfdf)

**Comment by Apnet66** [comment]
I have Stellarium installed not on Raspberry, but on a computer, I indicate its host. I can't install it on raspberries. in the browser, nothing is visible. I'm not an expert on raspberries (((

**Comment by kwahoo2** [comment]
It should still work. Open the browser on PI. If there is nothing, please check if Remote Control preferences are set as described in README, with "Access requires authentication" unchecked  https://raw.githubusercontent.com/kwahoo2/Mortar/master/.github/images/stellar-conf1.png

**Comment by Apnet66** [comment]
![17035318373696302460740963539082](https://github.com/kwahoo2/Mortar/assets/54183366/1f4a61c7-ebf2-4aa9-a1b1-2260ac3fac75)

**Comment by Apnet66** [comment]
I don't have Stellarium installed on the Pi. It's on the computer whose host I point to in Mortar

**Comment by kwahoo2** [comment]
It seems that Pi does not see the PC. Please try ping the PC from Pi:
`ping 192.168.0.106`
and then check open ports (also typing on Pi):
`nmap 192.168.0.106`

**Comment by Apnet66** [comment]
ping 56 (84) bytes of data
bash: nmap: command not found

**Comment by Apnet66** [comment]
apnet66@raspberrypi:~ $ nmap 192.168.0.106
Starting Nmap 7.93 ( https://nmap.org ) at 2023-12-25 23:56 
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.13 seconds

**Comment by Apnet66** [comment]
I removed the firewall and so on from the windows, looked at this (((

Starting Nmap 7.93 ( https://nmap.org ) at 2023-12-26 00:03 MSK
Nmap scan report for 192.168.0.106
Host is up (0.00056s latency).
Not shown: 993 closed tcp ports (conn-refused)
PORT     STATE SERVICE
135/tcp  open  msrpc
139/tcp  open  netbios-ssn
445/tcp  open  microsoft-ds
5357/tcp open  wsdapi
8090/tcp open  opsmessaging
8443/tcp open  https-alt
8800/tcp open  sunwebadmin

Nmap done: 1 IP address (1 host up) scanned in 0.20 seconds

**Comment by kwahoo2** [comment]
It seems that it should connect now:

> 8090/tcp open opsmessaging

If after opening in a browser http://192.168.0.106:8090/api/objects/listobjecttypes you can see some data, and `http://192.168.0.106:8090/api/objects/info?name=New Telescope 1&format=json` is still broken, then probably virtual telescope plugin configuration is incorrect.

**Comment by Apnet66** [comment]
Everything is fine, he sees the stellarium. Now I’m making drivers and transmitting GPS coordinates to Pi. Thank you. I'll figure it out further. Which joystick should I use?

**Comment by kwahoo2** [comment]
One of these cheap Dragorise-based gamepads. It should not matter as long Qt can recognize it. Also joystick is not really required, as you can use these arrow buttons in the Mortar window.
