### ISSUE TITLE
shield 8825 HAT

### ISSUE THREAD

**Issue by Apnet66** [kwahoo2/Mortar#3]
I connected the shield 8825 HAT and set it to 1/32 steps. Exactly the altitude gear ratio is 52.8? It works but I have questions.

**Comment by kwahoo2** [comment]
> Exactly the altitude gear ratio is 52.8?

Yes, two stage gearbox (264 teeth / 20 teeth) * (64 teeth / 16 teeth) = 52.8

**Comment by Apnet66** [comment]
Everything works as usual, but there is one drawback.  Doesn't show time with GPS.  coordinates, date available, time 00:00:00...when synchronized with GPS, Stellarium goes into the night...

**Comment by kwahoo2** [comment]
So it is, the GPS receiver->Mortar communication issue?
Uncomment line https://github.com/kwahoo2/Mortar/blob/master/StellarInterface.cpp#L92 You should see, in the terminal, raw data received from the GPS.

**Comment by Apnet66** [comment]
in unprocessed form, the time is transmitted correctly. In the time column, in Mortar, there are only zeros

**Comment by kwahoo2** [comment]
Can you post exact string?

Mortar expects:

`$GPGGA,064951.000,2307.1256,N,12016.4438,E,1,8,0.95,39.9,M,17.8,M,,*65`

with 10 character length time column
`064951.000`

**Comment by Apnet66** [comment]
yes, everything is in the data

вс, 11 февр. 2024 г., 13:45 kwahoo2 ***@***.***>:

**Comment by kwahoo2** [comment]
Can you post whole string?

**Comment by Apnet66** [comment]
вс, 11 февр. 2024 г., 17:55 Дмитрий Алексеев ***@***.***>:
