### ISSUE TITLE
Steps HAT8825

### ISSUE THREAD

**Issue by Apnet66** [kwahoo2/Mortar#6]
Still, the telescope lags behind the moon, and moves after it, but still lags behind.  There's something in the steps on the hat 8825...

**Comment by kwahoo2** [comment]
Does it move by the correct angle if you use manual control (with arrow buttons)? Eg. if you set the telescope tube horizontally and then change the altitude by 90 deg, will it move to the vertical position?

**Comment by Apnet66** [comment]
Here are the readings, raised 90 degrees and rotated horizontally 90 degrees.
![Uploading 17174333166708355962900531810496.jpg…]()

**Comment by kwahoo2** [comment]
The pic did not upload correctly.

**Comment by Apnet66** [comment]
![IMG_20240603_194434](https://github.com/kwahoo2/Mortar/assets/54183366/a7c17832-ff8e-4acd-a76c-bcc916e5c7ce)

**Comment by kwahoo2** [comment]
So, azimuth runs twice as fast as it should. Please check if microstepping is set to 1/32 (not 1/16).
Altitude is something more complicated, maybe combination of wrong sidestepping and missing steps? Please check if it is reproducible, going up and back down.

**Comment by Apnet66** [comment]
Thanks for the clever idea about 90 degrees.  Here are the settings under the hat. switches set to 1/32 (1-1-0) Tomorrow I'll check it on moving objects.
![1717529222689610896002646311397](https://github.com/kwahoo2/Mortar/assets/54183366/6c5056f7-56e1-450d-8d0b-e46f8dcb008e)
![17175293274294879559994550196406](https://github.com/kwahoo2/Mortar/assets/54183366/dbe3ac85-bb70-4746-b0fa-feae6492bbe4)

**Comment by Apnet66** [comment]
![Screenshot_20240604-223339__01](https://github.com/kwahoo2/Mortar/assets/54183366/d0b265a4-2cdb-453d-8c46-20251008ce14)
tried all combinations at 1/32

**Comment by kwahoo2** [comment]
> Thanks for the clever idea about 90 degrees. Here are the settings under the hat. switches set to 1/32 (1-1-0) Tomorrow I'll check it on moving objects. ![1717529222689610896002646311397](https://private-user-images.githubusercontent.com/54183366/336582859-6c5056f7-56e1-450d-8d0b-e46f8dcb008e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3ODI5MTMsIm5iZiI6MTcxNzc4MjYxMywicGF0aCI6Ii81NDE4MzM2Ni8zMzY1ODI4NTktNmM1MDU2ZjctNTZlMS00NTBkLThkMGItZTQ2ZjhkY2IwMDhlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE3NTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZDkyODFmOGNmN2VhYmI2YmY5ZTViYTQ3NmIzZjQzZjNjNTJkNGRjNGYxZDA4ZjA2NGFlZDA5ZGQ3MjAzN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wuWHf2s6Jvgd50tSjfFtEQqeGzM4dv-cdkYDbFwAmcY)


22 and 26.4 gear ratio, you don't use my gearbox setup, right?

**Comment by Apnet66** [comment]
I changed the steps from 400 to 200, and left the gear as you have 44 and 52.8.  Everything works at a 90 degree angle.  Changing the coefficient was the first thing that came to mind.  but he left it in place, still a mechanic... there is no normal sky yet.  I’ll definitely write when I try it.

**Comment by Apnet66** [comment]
![IMG-20240709-WA0002](https://github.com/kwahoo2/Mortar/assets/54183366/8311aa15-0ccd-4135-8110-0047d1d752c3)
everything works, no strong jerks.  True, with astrophotography, almost a third of the photo has to be deleted at a shutter speed of 0.5 seconds.  Takes good photos...
